// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1p_7fErC1S5vHS1bsdll9yM2J4UGkqZg',
    appId: '1:1038282697388:web:4f63441588b88396838d09',
    messagingSenderId: '1038282697388',
    projectId: 'send-packet-39197',
    authDomain: 'send-packet-39197.firebaseapp.com',
    storageBucket: 'send-packet-39197.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBimuAoGmRac8FHClcIQ0OtLwKBFrkf_Sw',
    appId: '1:1038282697388:android:0ae78a3fa5f5f5f8838d09',
    messagingSenderId: '1038282697388',
    projectId: 'send-packet-39197',
    storageBucket: 'send-packet-39197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5w5MWtkwF-pHrT_7zXoGOYh4E_gzbN2o',
    appId: '1:1038282697388:ios:a2fc4f54065e93fd838d09',
    messagingSenderId: '1038282697388',
    projectId: 'send-packet-39197',
    storageBucket: 'send-packet-39197.firebasestorage.app',
    iosBundleId: 'com.example.sendpacket.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5w5MWtkwF-pHrT_7zXoGOYh4E_gzbN2o',
    appId: '1:1038282697388:ios:f25b67a57db8be5f838d09',
    messagingSenderId: '1038282697388',
    projectId: 'send-packet-39197',
    storageBucket: 'send-packet-39197.firebasestorage.app',
    iosBundleId: 'com.example.sendpacket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1p_7fErC1S5vHS1bsdll9yM2J4UGkqZg',
    appId: '1:1038282697388:web:c78839f6e8886f02838d09',
    messagingSenderId: '1038282697388',
    projectId: 'send-packet-39197',
    authDomain: 'send-packet-39197.firebaseapp.com',
    storageBucket: 'send-packet-39197.firebasestorage.app',
  );
}
